// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnauvvkfpmtquaysfdvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuYXV2dmtmcG10cXVheXNmZHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNDM3ODMsImV4cCI6MjA1NjcxOTc4M30.8SOHVw4a6ht6AGycVYw4MjbBpNFXi7Rc3wvUJ717ZZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);